// @ts-check
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import cloudflare from '@astrojs/cloudflare';

// https://astro.build/config
// Sitemap is generated by the custom route at src/pages/sitemap.xml.ts which
// is the single source of truth. The @astrojs/sitemap integration was removed
// because in SSR mode it only sees a partial set of pages and was producing
// a stale /sitemap-index.xml + /sitemap-0.xml that exposed private routes
// (/account/*) and used trailing-slash URLs that conflicted with our canonical
// non-trailing-slash URLs.
export default defineConfig({
  site: 'https://mrnicevape.com',
  output: 'server',
  adapter: cloudflare(),
  integrations: [],
  vite: {
    plugins: [tailwindcss()]
  },
  build: {
    inlineStylesheets: 'auto',
  },
  compressHTML: true,
});